services:
  # Frontend web service
  - type: web
    name: running-events-hub-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: running-events-hub-api
          type: web
          property: url
        postfix: /api

  # Backend API service
  - type: web
    name: running-events-hub-api
    env: python
    region: ohio
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: running-events-db
          property: connectionString

# Database
databases:
  - name: running-events-db
    plan: free
    region: ohio 