services:
  # Frontend web service
  - type: web
    name: running-events-hub-frontend
    env: static
    buildCommand: cp -r frontend/* . && npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: running-events-hub-api
          type: web
          property: hostport
        prefix: https://
        postfix: /api

  # Backend API service
  - type: web
    name: running-events-hub-api
    env: python
    region: ohio
    buildCommand: pip install -r backend/requirements.txt
    startCommand: chmod +x backend/render_start.sh && ./backend/render_start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: ''
      - key: ALLOW_ALL_ORIGINS
        value: "true"

